/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karen, Isay, Sirio, Jesús.
 */
import java.sql.*;

public class Principal extends javax.swing.JFrame {
    //inicializamos las variables para realizar la conexión a la bd
    static Connection con = null;//Variable de la conexicón
    static Statement sta = null;//Estado de la conexión
    static ResultSet re = null;//Resutados de las consultas realizadas
    
    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        Centro = new javax.swing.JButton();
        Cliente = new javax.swing.JButton();
        Empleado = new javax.swing.JButton();
        Factura = new javax.swing.JButton();
        Pedido = new javax.swing.JButton();
        Plato = new javax.swing.JButton();
        Poblacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("COMO & COMO");

        label2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("@Copyright derechos reservados: Karen, Isay, Sirio, Jesús.");

        Centro.setText("Centro");
        Centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentroActionPerformed(evt);
            }
        });

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        Empleado.setText("Empleado");
        Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoActionPerformed(evt);
            }
        });

        Factura.setText("Factura");
        Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaActionPerformed(evt);
            }
        });

        Pedido.setText("Pedido");
        Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoActionPerformed(evt);
            }
        });

        Plato.setText("Plato");
        Plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatoActionPerformed(evt);
            }
        });

        Poblacion.setText("Poblacion");
        Poblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoblacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Centro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Empleado)))))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Poblacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Plato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Centro)
                    .addComponent(Pedido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cliente)
                    .addComponent(Plato))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Empleado)
                    .addComponent(Poblacion))
                .addGap(18, 18, 18)
                .addComponent(Factura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // implementación en codigo de la conexión a la base de datos
    public static Connection conexion(Connection con) throws SQLException{
        try{
            //inicialización de la conexión a jdbc
            Class.forName("oracle.jdbc.OracleDriver");
            //driver manejador de la conexión a la bd, con los atributos de nombre de usuario y contraseña
            con=DriverManager.getConnection("jdbc:oracle:thin:@172.72.39.103:1521:XE", "sysdba", "123");
        }
        catch (ClassNotFoundException e){
            System.out.println("No se pudo realizar la conexion");
        }
        return con;
    }
    
    public static Statement State (Statement sta) throws SQLException{
        //inicializa la conexión
        con=conexion(con);
        //crea un estado para la conexión. en este caso es "conectado" de lo contrario 
        //no entra aca y lanza la excepción con el mensaje: "No se pudo realizar la conexion"
        sta=con.createStatement();
        //regresa el estado de conexión: "conectado" 
        return sta;
    }
    
//Resultset para cada tabla, código para realizar las consultas con "select * from ..."
    public static ResultSet Resu (ResultSet re) throws SQLException{
        //consulta para centro
        sta=State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re=sta.executeQuery("select * from Centro");
        return re;
    }

    public static ResultSet ResuClie (ResultSet re) throws SQLException{
        //consulta para cliente
        sta = State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re = sta.executeQuery("select * from Cliente");
        return re;
    }

    public static ResultSet ResuEmple (ResultSet re) throws SQLException{
        //consulta para empleado
        sta = State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re = sta.executeQuery("select * from Empleado");
        return re;
    }

    public static ResultSet ResuFact (ResultSet re) throws SQLException{
        //consulta para factura
        sta = State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re = sta.executeQuery("select * from Factura");
        return re;
    }

    public static ResultSet ResuPedi (ResultSet re) throws SQLException{
        //consulta para pedido
        sta = State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re = sta.executeQuery("select * from Pedido");
        return re;
    }

    public static ResultSet ResuPlat (ResultSet re) throws SQLException{
        //consulta para plato
        sta = State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re = sta.executeQuery("select * from Plato");
        return re;
    }

    public static ResultSet Result(ResultSet re) throws SQLException{
        //Consulta para Población 
        sta=State(sta);
        //Comando de consulta tipo Query + comando en oracle para mostrar
        re=sta.executeQuery("select * from Poblacion");
        return re;
    }
    
    private void CentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentroActionPerformed
        // TODO add your handling code here:
        Centro cntro = new Centro();
        cntro.setVisible(true);
        cntro.pack();
    }//GEN-LAST:event_CentroActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
        Cliente clinte = new Cliente();
        clinte.setVisible(true);
        clinte.pack();
    }//GEN-LAST:event_ClienteActionPerformed

    private void EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActionPerformed
        // TODO add your handling code here:
        Empleado mpleado = new Empleado();
        mpleado.setVisible(true);
        mpleado.pack();
    }//GEN-LAST:event_EmpleadoActionPerformed

    private void FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaActionPerformed
        // TODO add your handling code here:
        Factura fctura = new Factura();
        fctura.setVisible(true);
        fctura.pack();
    }//GEN-LAST:event_FacturaActionPerformed

    private void PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoActionPerformed
        // TODO add your handling code here:
        Pedido pdido = new Pedido();
        pdido.setVisible(true);
        pdido.pack();
    }//GEN-LAST:event_PedidoActionPerformed

    private void PlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatoActionPerformed
        // TODO add your handling code here:
        Plato plto = new Plato();
        plto.setVisible(true);
        plto.pack();
    }//GEN-LAST:event_PlatoActionPerformed

    private void PoblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoblacionActionPerformed
        // TODO add your handling code here:
        Poblacion pblacion = new Poblacion();
        pblacion.setVisible(true);
        pblacion.pack();
    }//GEN-LAST:event_PoblacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Centro;
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Empleado;
    private javax.swing.JButton Factura;
    private javax.swing.JButton Pedido;
    private javax.swing.JButton Plato;
    private javax.swing.JButton Poblacion;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
